version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitboard_app_1
      APP_PORT: 3711

  app:
    image: ghcr.io/egzola/bitboard:1.0.0@sha256:9d390c1aa9025a49c37604239700662236b8fc84138ae582fa66710ac4a82bf7
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: 3711
    volumes:
      - ${APP_DATA_DIR}/data:/data
